[entryPoints]
  [entryPoints.web]
    address = ":8080"
  [entryPoints.websecure]
    address = ":8443"

[api]
  insecure = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
